[package]
name = "jeeves"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonic = "0.2.12"
simple-websockets = "0.1.6"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "s"  # Optimize for size.
lto = true
codegen-units = 1
panic = "abort"
